/*
    Generated by PseudoForge.
    Version: <VERSION>
    Preview/export only. IDB was not modified.
    Function: sub_140003530
    Fingerprint: <FINGERPRINT>
    Rename candidates: 7
    Flow rewrites: 0
    Kernel semantic rewrites: 4
    Warnings: 0
    Kernel insights:
      - driver_entry: DriverEntry-style dispatch table, unload routine, and device creation sequence detected confidence=0.92
      - driver_dispatch_table: IRP major-function table initialization is present confidence=0.90
      - device_extension_layout: DeviceExtension field offsets can be rendered as a preview-only inferred driver extension confidence=0.84
    Renames: DeferredContext->extension(0.93,kernel-driver-entry), DestinationString->deviceName(0.93,kernel-driver-entry), DeviceObject->deviceObject(0.93,kernel-driver-entry), a1->driverObject(0.99,prototype), a2->registryPath(0.99,prototype), i->majorIndex(0.93,kernel-driver-entry), v3->status(0.94,kernel-status)
*/

#ifndef PSEUDOFORGE_POOL_TAG
#define PSEUDOFORGE_POOL_TAG(a, b, c, d) ((ULONG)(a) | ((ULONG)(b) << 8) | ((ULONG)(c) << 16) | ((ULONG)(d) << 24))
#endif
#ifndef POOL_TAG
#define POOL_TAG(a, b, c, d) PSEUDOFORGE_POOL_TAG(a, b, c, d)
#endif
// PseudoForge: inferred driver device extension from DriverEntry offset usage.
// Preview-only: this does not imply the original source struct name or sizeof expression.
typedef struct _INFERRED_DRIVER_DEVICE_EXTENSION
{
  ULONG Signature;
  PDEVICE_OBJECT DeviceObject;
  FAST_MUTEX StateLock;
  FAST_MUTEX AccessListLock;
  KSPIN_LOCK EventLock;
  LIST_ENTRY EventList;
  LIST_ENTRY ProcessWhitelist;
  LIST_ENTRY ProcessBlacklist;
  NPAGED_LOOKASIDE_LIST RecordLookaside;
  NPAGED_LOOKASIDE_LIST ProcessRuleLookaside;
  KTIMER Timer;
  KDPC TimerDpc;
  PIO_WORKITEM WorkItem;
  KEVENT WorkItemIdleEvent;
  EX_RUNDOWN_REF Rundown;
  ERESOURCE Resource;
  UNICODE_STRING RegistryPath;
  ULONG MaxRecords;
  UCHAR ReservedTail[0x5C];
} INFERRED_DRIVER_DEVICE_EXTENSION;

NTSTATUS __fastcall DriverEntry(
        PDRIVER_OBJECT driverObject,
        PUNICODE_STRING registryPath)
{
  NTSTATUS status; // [rsp+40h] [rbp-38h]
  unsigned int majorIndex; // [rsp+44h] [rbp-34h]
  INFERRED_DRIVER_DEVICE_EXTENSION *extension; // [rsp+48h] [rbp-30h]
  PDEVICE_OBJECT deviceObject; // [rsp+50h] [rbp-28h] BYREF
  struct _UNICODE_STRING deviceName; // [rsp+58h] [rbp-20h] BYREF

  deviceObject = 0LL;
  extension = 0LL;
  RtlInitUnicodeString(&deviceName, L"\\Device\\PfKernelPattern");
  RtlInitUnicodeString(&SymbolicLinkName, L"\\DosDevices\\PfKernelPattern");
  for ( majorIndex = 0; majorIndex <= IRP_MJ_MAXIMUM_FUNCTION; ++majorIndex )
  {
    driverObject->MajorFunction[majorIndex] = (PDRIVER_DISPATCH)sub_140003430;
  }
  driverObject->MajorFunction[IRP_MJ_CREATE] = (PDRIVER_DISPATCH)sub_1400011D0;
  driverObject->MajorFunction[IRP_MJ_CLOSE] = (PDRIVER_DISPATCH)sub_1400011D0;
  driverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL] = (PDRIVER_DISPATCH)sub_1400013F0;
  driverObject->DriverUnload = (PDRIVER_UNLOAD)sub_140003270;
  status = IoCreateDevice(driverObject, 0x340u, &deviceName, 0x8337u, FILE_DEVICE_SECURE_OPEN, FALSE, &deviceObject);
  if ( NT_SUCCESS(status) )
  {
    deviceObject->Flags |= DO_BUFFERED_IO;
    extension = deviceObject->DeviceExtension;
    memset(extension, 0, 0x340uLL);
    extension->Signature = POOL_TAG('P', 'F', 'K', 'p');
    extension->DeviceObject = deviceObject;
    extension->MaxRecords = 64;
    qword_140005010 = (__int64)deviceObject;
    ExInitializeFastMutex(&extension->StateLock);
    ExInitializeFastMutex(&extension->AccessListLock);
    KeInitializeSpinLock(&extension->EventLock);
    InitializeListHead(&extension->EventList);
    InitializeListHead(&extension->ProcessWhitelist);
    InitializeListHead(&extension->ProcessBlacklist);
    ExInitializeNPagedLookasideList(&extension->RecordLookaside, 0LL, 0LL, 0, 0x38uLL, POOL_TAG('P', 'F', 'K', 'r'), 0);
    ExInitializeNPagedLookasideList(&extension->ProcessRuleLookaside, 0LL, 0LL, 0, 0x28uLL, POOL_TAG('P', 'F', 'K', 'l'), 0);
    KeInitializeTimerEx(&extension->Timer, NotificationTimer);
    KeInitializeDpc(&extension->TimerDpc, DeferredRoutine, extension);
    KeInitializeEvent(&extension->WorkItemIdleEvent, NotificationEvent, TRUE);
    ExInitializeRundownProtection(&extension->Rundown);
    ExInitializeResourceLite(&extension->Resource);
    status = sub_140002D60(extension);
    if ( NT_SUCCESS(status) )
    {
      status = sub_1400010D0(&extension->RegistryPath, registryPath);
      if ( NT_SUCCESS(status) )
      {
        sub_140002950(extension);
        extension->WorkItem = IoAllocateWorkItem(deviceObject);
        if ( extension->WorkItem )
        {
          status = IoCreateSymbolicLink(&SymbolicLinkName, &deviceName);
          if ( NT_SUCCESS(status) )
          {
            deviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
          }
        }
        else
        {
          status = STATUS_INSUFFICIENT_RESOURCES;
        }
      }
    }
  }
  if ( !NT_SUCCESS(status) )
  {
    if ( extension )
    {
      if ( extension->WorkItem )
      {
        IoFreeWorkItem(extension->WorkItem);
        extension->WorkItem = 0LL;
      }
      if ( extension->RegistryPath.Buffer )
      {
        ExFreePoolWithTag(extension->RegistryPath.Buffer, POOL_TAG('P', 'F', 'K', 'p'));
        memset(&extension->RegistryPath, 0, sizeof(extension->RegistryPath));
      }
      ExDeleteResourceLite(&extension->Resource);
      sub_140001310(extension);
      ExDeleteNPagedLookasideList(&extension->ProcessRuleLookaside);
      ExDeleteNPagedLookasideList(&extension->RecordLookaside);
    }
    if ( deviceObject )
    {
      IoDeleteDevice(deviceObject);
      qword_140005010 = 0LL;
    }
  }
  return status;
}
