/*
    Generated by PseudoForge.
    Version: <VERSION>
    Preview/export only. IDB was not modified.
    Function: SingleLineIfSample
    Fingerprint: <FINGERPRINT>
    Rename candidates: 1
    Flow rewrites: 0
    Kernel semantic rewrites: 0
    Warnings: 0
    Renames: a1->argument0(0.82,prototype)
*/


__int64 __fastcall SingleLineIfSample(int argument0)
{
  int v1;

  v1 = 0;
  if ( argument0 )
  {
    *(_BYTE *)(v1 + 10) = 1;
  }
  v1 = ZwLoadDriver(&DriverServiceName);
  return v1;
}
