/*
    Generated by PseudoForge.
    Version: <VERSION>
    Preview/export only. IDB was not modified.
    Function: PfkpObjectPreOperation
    Fingerprint: <FINGERPRINT>
    Rename candidates: 2
    Flow rewrites: 0
    Kernel semantic rewrites: 0
    Warnings: 0
    Renames: a1->registrationContext(0.99,prototype), a2->preOperationInfo(0.99,prototype)
*/


OB_PREOP_CALLBACK_STATUS __fastcall PfkpObjectPreOperation(
        PVOID registrationContext,
        POB_PRE_OPERATION_INFORMATION preOperationInfo)
{
  unsigned int desiredAccess;

  desiredAccess = 0;
  if ( preOperationInfo->Operation == 1 )
  {
    desiredAccess = preOperationInfo->Parameters->CreateHandleInformation.OriginalDesiredAccess;
  }
  else
  {
    if ( preOperationInfo->Operation == 2 )
    {
      desiredAccess = preOperationInfo->Parameters->DuplicateHandleInformation.OriginalDesiredAccess;
    }
  }
  return OB_PREOP_SUCCESS;
}
