from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path
from typing import Any


DEFAULT_WDK_INCLUDE_ROOT = Path(r"C:\Program Files (x86)\Windows Kits\10\Include")
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "ida_pseudoforge" / "profiles" / "kernel_api.json"
DEFAULT_HEADER_DIRS = ["km", "shared"]
SPLIT_PROFILE_FILES = {
    "functions": "kernel_functions.json",
    "enums": "kernel_enums.json",
    "structures": "kernel_structures.json",
    "aliases": "kernel_aliases.json",
    "macros": "kernel_macros.json",
    "symbols": "kernel_symbol_index.json",
    "indices": "kernel_indices.json",
}


FUNCTION_SEMANTICS = {
    "ExAllocatePool2": {
        "params": [
            {"name": "Flags", "kind": "flags", "enum": "POOL_FLAGS"},
            {"name": "NumberOfBytes", "kind": "size"},
            {"name": "Tag", "kind": "pool_tag"},
        ],
    },
    "ExAllocatePool3": {
        "params": [
            {"name": "Flags", "kind": "flags", "enum": "POOL_FLAGS"},
            {"name": "NumberOfBytes", "kind": "size"},
            {"name": "Tag", "kind": "pool_tag"},
            {"name": "ExtendedParameters", "kind": "pointer"},
            {"name": "ExtendedParametersCount", "kind": "count"},
        ],
    },
    "ExFreePoolWithTag": {
        "params": [
            {"name": "P", "kind": "pointer"},
            {"name": "Tag", "kind": "pool_tag"},
        ],
    },
    "ExAcquireResourceExclusiveLite": {
        "params": [
            {"name": "Resource", "kind": "pointer"},
            {"name": "Wait", "kind": "bool", "enum": "BOOLEAN"},
        ],
    },
    "ExReleaseResourceLite": {
        "params": [
            {"name": "Resource", "kind": "pointer"},
        ],
    },
    "InitializeListHead": {
        "params": [
            {"name": "ListHead", "kind": "pointer"},
        ],
    },
    "RemoveEntryList": {
        "params": [
            {"name": "Entry", "kind": "pointer"},
        ],
    },
    "InsertTailList": {
        "params": [
            {"name": "ListHead", "kind": "pointer"},
            {"name": "Entry", "kind": "pointer"},
        ],
    },
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Build PseudoForge kernel API profile from local WDK headers.")
    parser.add_argument("--wdk-include-root", default=str(DEFAULT_WDK_INCLUDE_ROOT))
    parser.add_argument("--version", default="")
    parser.add_argument("--header", action="append", dest="headers", default=[])
    parser.add_argument("--all-km-headers", action="store_true")
    parser.add_argument("--directory", action="append", dest="directories", default=[])
    parser.add_argument("--out", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--split-output-dir", default="")
    parser.add_argument("--split-only", action="store_true")
    parser.add_argument("--function", action="append", dest="functions", default=[])
    parser.add_argument("--known-only", action="store_true")
    parser.add_argument("--list-versions", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--summary", action="store_true")
    parser.add_argument("--verbose-summary", action="store_true")
    args = parser.parse_args()
    if args.split_only and not args.split_output_dir:
        parser.error("--split-only requires --split-output-dir")

    include_root = Path(args.wdk_include_root)
    if args.list_versions:
        for version in _list_wdk_versions(include_root):
            print(version)
        return 0

    version_dir = _find_wdk_version_dir(include_root, args.version)
    header_paths = _resolve_header_paths(version_dir, args.headers, args.directories, args.all_km_headers)
    header_texts = [(path, path.read_text(encoding="utf-8", errors="replace")) for path in header_paths]
    functions = args.functions or (list(FUNCTION_SEMANTICS) if args.known_only else [])
    enums = _build_enums(header_texts)
    structures = _build_structures(header_texts)
    function_map = _build_functions(header_texts, functions)
    macros = _build_macros(header_texts)
    aliases = _build_aliases(header_texts)

    profile = {
        "schema_version": 2,
        "source": {
            "kind": "wdk-generated",
            "wdk_version": version_dir.name,
            "header_directories": _header_directories_for_source(version_dir, header_paths),
            "headers": [str(path) for path in header_paths],
            "notes": "Generated by tools/build_kernel_api_profile.py from local WDK headers.",
        },
        "functions": function_map,
        "enums": enums,
        "structures": structures,
        "aliases": aliases,
        "macros": macros,
    }
    profile["symbols"] = _build_symbol_index(profile)
    profile["indices"] = _build_indices(profile)

    if args.summary:
        _print_summary(profile, verbose=args.verbose_summary)

    if args.dry_run:
        print(json.dumps(profile, indent=2, sort_keys=True))
        return 0

    if not args.split_only:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(profile, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        print("wrote %s from %d WDK headers" % (out_path, len(header_paths)))
    if args.split_output_dir:
        split_paths = _write_split_profile_files(profile, Path(args.split_output_dir))
        print("wrote %d split profile files to %s" % (len(split_paths), Path(args.split_output_dir)))
    return 0


def _split_kernel_api_profile(profile: dict[str, Any]) -> dict[str, dict[str, Any]]:
    result = {}
    for family, file_name in SPLIT_PROFILE_FILES.items():
        payload = profile.get(family, {})
        result[file_name] = payload if isinstance(payload, dict) else {}
    return result


def _write_split_profile_files(profile: dict[str, Any], output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for file_name, payload in _split_kernel_api_profile(profile).items():
        path = output_dir / file_name
        path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        paths.append(path)
    return paths


def _list_wdk_versions(include_root: Path) -> list[str]:
    if not include_root.exists():
        return []
    return sorted(path.name for path in include_root.glob("10.*.*.*") if (path / "km" / "wdm.h").exists())


def _find_wdk_version_dir(include_root: Path, version: str) -> Path:
    if version:
        candidate = include_root / version
        if candidate.exists():
            return candidate
        raise FileNotFoundError(candidate)

    candidates = sorted(path for path in include_root.glob("10.*.*.*") if (path / "km").exists())
    if not candidates:
        raise FileNotFoundError("No WDK version directory under %s" % include_root)
    return candidates[-1]


def _resolve_header_paths(version_dir: Path, headers: list[str], directories: list[str], all_km_headers: bool) -> list[Path]:
    if all_km_headers:
        return sorted((version_dir / "km").glob("*.h"))

    if not headers:
        selected_dirs = directories or DEFAULT_HEADER_DIRS
        paths = []
        for directory in selected_dirs:
            header_dir = version_dir / directory
            if not header_dir.exists():
                print("warning: WDK header directory not found: %s" % header_dir, file=sys.stderr)
                continue
            paths.extend(sorted(header_dir.glob("*.h")))
        if not paths:
            raise FileNotFoundError("No selected WDK headers found under %s" % version_dir)
        return _dedupe_paths(paths)

    paths = []
    for header in headers:
        path = Path(header)
        candidate = path if path.is_absolute() else _find_named_header(version_dir, header)
        if not candidate.exists():
            print("warning: WDK header not found: %s" % candidate, file=sys.stderr)
            continue
        paths.append(candidate)
    if not paths:
        raise FileNotFoundError("No selected WDK headers found under %s" % version_dir)
    return _dedupe_paths(paths)


def _find_named_header(version_dir: Path, header: str) -> Path:
    for directory in DEFAULT_HEADER_DIRS + ["um"]:
        candidate = version_dir / directory / header
        if candidate.exists():
            return candidate
    return version_dir / "km" / header


def _dedupe_paths(paths: list[Path]) -> list[Path]:
    result = []
    seen = set()
    for path in paths:
        key = str(path).lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(path)
    return result


def _header_directories_for_source(version_dir: Path, header_paths: list[Path]) -> list[str]:
    directories = []
    seen = set()
    for path in header_paths:
        try:
            relative = path.relative_to(version_dir)
            directory = str(relative.parent)
        except ValueError:
            directory = str(path.parent)
        if directory.lower() in seen:
            continue
        seen.add(directory.lower())
        directories.append(directory)
    return directories


def _extract_pool_flags(text: str) -> dict[str, str]:
    flags = {}
    pattern = re.compile(r"^#define\s+(POOL_FLAG_[A-Z0-9_]+)\s+(0x[0-9A-Fa-f]+|\d+)[A-Za-z0-9_]*", re.MULTILINE)
    ignored = {
        "POOL_FLAG_REQUIRED_START",
        "POOL_FLAG_REQUIRED_END",
        "POOL_FLAG_OPTIONAL_START",
        "POOL_FLAG_OPTIONAL_END",
        "POOL_FLAG_REQUIRED_MASK",
        "POOL_FLAG_UNUSED_REQUIRED_BITS",
        "POOL_FLAG_LAST_KNOWN_REQUIRED",
    }
    for match in pattern.finditer(text):
        name = match.group(1)
        if name in ignored or name.startswith("POOL_FLAG_RESERVED"):
            continue
        value = int(match.group(2), 0)
        flags[str(value)] = name
    return flags


def _build_enums(header_texts: list[tuple[Path, str]]) -> dict[str, dict[str, str]]:
    enums = {
        "BOOLEAN": {
            "0": "FALSE",
            "1": "TRUE",
        },
    }
    for _header_path, text in header_texts:
        _merge_enum_values(enums, "POOL_FLAGS", _extract_pool_flags(text))
        for name, values in _extract_typedef_enums(text).items():
            _merge_enum_values(enums, name, values)
    return enums


def _merge_enum_values(enums: dict[str, dict[str, str]], name: str, values: dict[str, str]) -> None:
    if not values:
        return
    target = enums.setdefault(name, {})
    for value, member_name in values.items():
        target.setdefault(str(value), str(member_name))


def _build_structures(header_texts: list[tuple[Path, str]]) -> dict[str, dict[str, object]]:
    structures: dict[str, dict[str, object]] = {}
    for header_path, text in header_texts:
        for name, metadata in _extract_typedef_structs(text, header_path).items():
            structures.setdefault(name, metadata)
    structures["LIST_ENTRY"] = {
        "fields": [
            {"offset": 0, "type": "PLIST_ENTRY", "name": "Flink"},
            {"offset": 8, "type": "PLIST_ENTRY", "name": "Blink"},
        ],
    }
    structures.setdefault("ERESOURCE", {"opaque": True})
    return structures


def _build_functions(header_texts: list[tuple[Path, str]], function_names: list[str]) -> dict[str, dict[str, object]]:
    functions = {}
    if function_names:
        for name in function_names:
            declaration = None
            declaration_header = None
            for header_path, text in header_texts:
                declaration = _extract_function_declaration(text, name)
                if declaration is not None:
                    declaration_header = header_path
                    break
            if declaration is None or declaration_header is None:
                print("warning: function not found in WDK header: %s" % name, file=sys.stderr)
                continue
            functions[name] = _merge_function_semantics(name, declaration, declaration_header)
        return functions

    for header_path, text in header_texts:
        for name, declaration in _extract_function_declarations(text).items():
            functions.setdefault(name, _merge_function_semantics(name, declaration, header_path))
    return functions


def _extract_function_declaration(text: str, function_name: str) -> dict[str, Any] | None:
    scan_text = _function_declaration_scan_text(text)
    pattern = re.compile(r"\b%s\s*\(" % re.escape(function_name))
    for match in pattern.finditer(scan_text):
        declaration = _extract_function_declaration_from_match(text, scan_text, match)
        if declaration is not None:
            return declaration
    return None


def _extract_function_declarations(text: str) -> dict[str, dict[str, Any]]:
    declarations = {}
    scan_text = _function_declaration_scan_text(text)
    pattern = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(")
    for match in pattern.finditer(scan_text):
        name = match.group(1)
        if name in declarations:
            continue
        if _is_ignored_function_candidate(name):
            continue
        declaration = _extract_function_declaration_from_match(text, scan_text, match)
        if declaration is None:
            continue
        declarations[name] = declaration
    return declarations


def _extract_function_declaration_from_match(
    text: str,
    scan_text: str,
    match: re.Match[str],
) -> dict[str, Any] | None:
    function_name = match.group(1) if match.lastindex else match.group(0).split("(")[0].strip()
    if _is_ignored_function_candidate(function_name):
        return None
    line_start = scan_text.rfind("\n", 0, match.start()) + 1
    if scan_text[line_start : match.start()].lstrip().startswith("#define"):
        return None

    open_index = scan_text.find("(", match.start())
    close_index = _find_matching_parenthesis(scan_text, open_index)
    if close_index < 0:
        return None
    semicolon_index = scan_text.find(";", close_index)
    if semicolon_index < 0:
        brace_index = scan_text.find("{", close_index)
        end_index = brace_index if brace_index >= 0 else close_index
    else:
        end_index = semicolon_index + 1

    start_index = _find_declaration_start(scan_text, match.start())
    raw = scan_text[start_index:end_index].strip()
    if not _looks_like_function_declaration(raw, function_name):
        return None
    prefix = scan_text[start_index:match.start()].strip()
    return_type, calling_convention = _parse_return_type(prefix)
    if not return_type:
        return None
    if any(char in return_type for char in "{}(),;"):
        return None
    if _looks_like_prose_type(return_type):
        return None
    args = scan_text[open_index + 1 : close_index]
    params = _parse_parameter_list(args)
    return {
        "raw_signature": _normalize_space(raw),
        "return_type": return_type,
        "calling_convention": calling_convention,
        "params": params,
    }


def _is_ignored_function_candidate(name: str) -> bool:
    if name.startswith("_"):
        return True
    return name in {
        "if",
        "for",
        "while",
        "switch",
        "return",
        "sizeof",
        "defined",
        "typedef",
        "deprecated",
        "warning",
        "const_seg",
        "features",
        "s",
    }


def _looks_like_function_declaration(raw: str, function_name: str) -> bool:
    if "typedef" in raw[: raw.find(function_name)]:
        return False
    if "{" in raw[: raw.find(function_name)]:
        return False
    markers = (
        "NTKERNELAPI",
        "NTSYSAPI",
        "FORCEINLINE",
        "CFORCEINLINE",
        "__kernel_entry",
        "DECLSPEC_IMPORT",
        "EXPORT",
        "NTAPI",
        "FASTCALL",
        "FLTAPI",
        "WMIAPI",
    )
    return any(marker in raw for marker in markers)


def _merge_function_semantics(function_name: str, declaration: dict[str, Any], header_path: Path) -> dict[str, Any]:
    semantics = FUNCTION_SEMANTICS.get(function_name, {})
    semantic_params = semantics.get("params", []) if isinstance(semantics, dict) else []
    parsed_params = declaration.get("params", [])
    params = []
    for index, parsed in enumerate(parsed_params):
        semantic = semantic_params[index] if index < len(semantic_params) and isinstance(semantic_params[index], dict) else {}
        param = {
            "name": parsed.get("name") or semantic.get("name") or "param%d" % index,
            "type": parsed.get("type") or semantic.get("type") or "",
        }
        param["kind"] = semantic.get("kind") or _infer_parameter_kind(function_name, param)
        enum_name = semantic.get("enum")
        if not enum_name and param["kind"] == "bool":
            enum_name = "BOOLEAN"
        if enum_name:
            param["enum"] = enum_name
        params.append(param)

    result = {
        "header": header_path.name,
        "source_header": str(header_path),
        "return_type": declaration.get("return_type", ""),
        "raw_signature": declaration.get("raw_signature", ""),
        "params": params,
    }
    calling_convention = declaration.get("calling_convention", "")
    if calling_convention:
        result["calling_convention"] = calling_convention
    return result


def _infer_parameter_kind(function_name: str, param: dict[str, Any]) -> str:
    param_name = str(param.get("name", "")).strip()
    param_type = str(param.get("type", "")).upper()
    normalized_type = re.sub(r"\b(IN|OUT|OPTIONAL|CONST)\b", " ", param_type)
    normalized_type = re.sub(r"\s+", " ", normalized_type).strip()
    if param_name == "Tag" and "ULONG" in normalized_type:
        lowered_name = function_name.lower()
        if "withtag" in lowered_name or "pool" in lowered_name:
            return "pool_tag"
    if re.fullmatch(r"(?:_LITERAL_ )?BOOLEAN", normalized_type):
        return "bool"
    return "value"


def _build_macros(header_texts: list[tuple[Path, str]]) -> dict[str, dict[str, object]]:
    macros: dict[str, dict[str, object]] = {}
    for header_path, text in header_texts:
        for name, metadata in _extract_macros(text, header_path).items():
            macros.setdefault(name, metadata)
    return macros


def _extract_macros(text: str, header_path: Path) -> dict[str, dict[str, object]]:
    macros: dict[str, dict[str, object]] = {}
    for line in _logical_preprocessor_lines(text):
        match = re.match(r"#\s*define\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)(?P<args>\([^)]*\))?\s*(?P<value>.*)$", line)
        if match is None:
            continue
        name = match.group("name")
        if name.startswith("_") and not name.startswith("__"):
            continue
        value = _normalize_space(_strip_comments(match.group("value")))
        if len(value) > 300:
            value = value[:300] + "..."
        metadata: dict[str, object] = {
            "source_header": str(header_path),
            "value": value,
        }
        args = match.group("args")
        if args:
            metadata["function_like"] = True
            metadata["params"] = [item.strip() for item in args.strip("()").split(",") if item.strip()]
        numeric_value = _eval_int_expression(value, {})
        if numeric_value is not None:
            metadata["integer"] = numeric_value
        macros[name] = metadata
    return macros


def _logical_preprocessor_lines(text: str) -> list[str]:
    lines = []
    current = []
    for line in text.splitlines():
        stripped = line.rstrip()
        if current:
            current.append(stripped.rstrip("\\"))
        else:
            if not stripped.lstrip().startswith("#"):
                continue
            current.append(stripped.rstrip("\\"))
        if stripped.endswith("\\"):
            continue
        lines.append(" ".join(current))
        current = []
    if current:
        lines.append(" ".join(current))
    return lines


def _build_aliases(header_texts: list[tuple[Path, str]]) -> dict[str, dict[str, object]]:
    aliases: dict[str, dict[str, object]] = {}
    for header_path, text in header_texts:
        for name, metadata in _extract_typedef_aliases(text, header_path).items():
            aliases.setdefault(name, metadata)
        for name, metadata in _extract_compound_typedef_aliases(text, header_path).items():
            aliases.setdefault(name, metadata)
    return aliases


def _extract_typedef_aliases(text: str, header_path: Path) -> dict[str, dict[str, object]]:
    aliases: dict[str, dict[str, object]] = {}
    stripped = _strip_comments(text)
    tag_pattern = re.compile(r"typedef\s+(?P<kind>struct|enum|union)\s+(?P<tag>_[A-Za-z][A-Za-z0-9_]*)\s+(?P<aliases>[^;{}()]+);")
    for match in tag_pattern.finditer(stripped):
        target = _normalize_type_name(match.group("tag"))
        for alias_text in _split_arguments(match.group("aliases")):
            alias_text = _normalize_space(alias_text)
            alias_match = re.match(r"(?P<pointer>\*+)?\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", alias_text)
            if alias_match is None:
                continue
            name = alias_match.group("name")
            pointer = alias_match.group("pointer") or ""
            aliases[name] = {
                "target": target + (" " + pointer if pointer else ""),
                "kind": match.group("kind"),
                "source_header": str(header_path),
            }

    pattern = re.compile(r"typedef\s+(?P<target>[^;{}()]+?)\s+(?P<aliases>[^;{}()]+);")
    for match in pattern.finditer(stripped):
        target = _normalize_space(match.group("target"))
        if not target or target in {"struct", "enum", "union"}:
            continue
        for alias_text in _split_arguments(match.group("aliases")):
            alias_text = _normalize_space(alias_text)
            alias_match = re.match(r"(?P<pointer>\*+)?\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", alias_text)
            if alias_match is None:
                continue
            name = alias_match.group("name")
            pointer = alias_match.group("pointer") or ""
            aliases[name] = {
                "target": target + (" " + pointer if pointer else ""),
                "source_header": str(header_path),
            }
    return aliases


def _extract_compound_typedef_aliases(text: str, header_path: Path) -> dict[str, dict[str, object]]:
    aliases: dict[str, dict[str, object]] = {}
    stripped = _strip_comments(text)
    pattern = re.compile(r"typedef\s+(?P<kind>struct|enum|union)(?:\s+(?P<tag>_[A-Za-z][A-Za-z0-9_]*))?\s*\{.*?\}\s*(?P<aliases>[^;]+);", re.DOTALL)
    for match in pattern.finditer(stripped):
        tag = match.group("tag") or ""
        target = _normalize_type_name(tag) if tag else match.group("kind")
        for alias_text in _split_arguments(match.group("aliases")):
            alias_text = _normalize_space(alias_text)
            alias_match = re.match(r"(?P<pointer>\*+)?\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", alias_text)
            if alias_match is None:
                continue
            name = alias_match.group("name")
            pointer = alias_match.group("pointer") or ""
            aliases[name] = {
                "target": target + (" " + pointer if pointer else ""),
                "kind": match.group("kind"),
                "source_header": str(header_path),
            }
    return aliases


def _build_symbol_index(profile: dict[str, Any]) -> dict[str, list[dict[str, object]]]:
    symbols: dict[str, list[dict[str, object]]] = {}

    def add(name: str, entry: dict[str, object]) -> None:
        if not name:
            return
        symbols.setdefault(name, []).append(entry)

    for name, metadata in _dict_items(profile.get("functions")):
        add(name, {"kind": "function", "header": metadata.get("header", ""), "name": name})
    for name, metadata in _dict_items(profile.get("structures")):
        add(name, {"kind": "structure", "header": Path(str(metadata.get("source_header", ""))).name, "name": name})
    for name, metadata in _dict_items(profile.get("aliases")):
        add(name, {"kind": "alias", "target": metadata.get("target", ""), "name": name})
    for name, metadata in _dict_items(profile.get("macros")):
        add(name, {"kind": "macro", "header": Path(str(metadata.get("source_header", ""))).name, "name": name})
    for enum_name, values in _dict_items(profile.get("enums")):
        add(enum_name, {"kind": "enum", "name": enum_name})
        if isinstance(values, dict):
            for value, member_name in values.items():
                add(str(member_name), {"kind": "enum_member", "enum": enum_name, "value": str(value), "name": str(member_name)})
    return symbols


def _build_indices(profile: dict[str, Any]) -> dict[str, object]:
    header_index: dict[str, dict[str, list[str]]] = {}

    def add_header_symbol(kind: str, header: str, name: str) -> None:
        if not header:
            return
        entry = header_index.setdefault(header, {"functions": [], "structures": [], "macros": []})
        entry.setdefault(kind, []).append(name)

    for name, metadata in _dict_items(profile.get("functions")):
        add_header_symbol("functions", str(metadata.get("header", "")), name)
    for name, metadata in _dict_items(profile.get("structures")):
        add_header_symbol("structures", Path(str(metadata.get("source_header", ""))).name, name)
    for name, metadata in _dict_items(profile.get("macros")):
        add_header_symbol("macros", Path(str(metadata.get("source_header", ""))).name, name)

    prefixes = {
        "Ex": [],
        "Ke": [],
        "Mm": [],
        "Ob": [],
        "Ps": [],
        "Io": [],
        "Zw": [],
        "Flt": [],
        "Ndis": [],
        "StorPort": [],
        "Wdf": [],
    }
    functions = profile.get("functions", {})
    rewrite_functions = []
    if isinstance(functions, dict):
        for name, metadata in functions.items():
            if _function_has_semantic_rewrite(metadata):
                rewrite_functions.append(name)
            for prefix in prefixes:
                if name.startswith(prefix):
                    prefixes[prefix].append(name)
                    break
    return {
        "headers": {name: {kind: sorted(values) for kind, values in metadata.items()} for name, metadata in sorted(header_index.items())},
        "function_prefixes": {prefix: sorted(values) for prefix, values in prefixes.items() if values},
        "rewrite_functions": sorted(rewrite_functions),
    }


def _function_has_semantic_rewrite(metadata: object) -> bool:
    if not isinstance(metadata, dict):
        return False
    params = metadata.get("params", [])
    if not isinstance(params, list):
        return False
    for param in params:
        if isinstance(param, dict) and param.get("kind") in {"flags", "pool_tag", "bool"}:
            return True
    return False


def _dict_items(value: object):
    if isinstance(value, dict):
        return value.items()
    return []


def _extract_typedef_enums(text: str) -> dict[str, dict[str, str]]:
    enums = {}
    pattern = re.compile(r"typedef\s+enum(?:\s+(?P<tag>_[A-Za-z][A-Za-z0-9_]*))?\s*\{(?P<body>.*?)\}\s*(?P<aliases>[^;]+);", re.DOTALL)
    for match in pattern.finditer(_strip_comments(text)):
        tag = match.group("tag") or ""
        aliases = match.group("aliases")
        name = _select_typedef_name(tag, aliases)
        if not name:
            continue
        values = _parse_enum_values(match.group("body"))
        if values:
            enums[name] = values
    return enums


def _parse_enum_values(body: str) -> dict[str, str]:
    values = {}
    symbols: dict[str, int] = {}
    current = -1
    for item in _split_arguments(body):
        item = item.strip()
        if not item:
            continue
        item = re.sub(r"\s+", " ", item)
        match = re.match(r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)(?:\s*=\s*(?P<expr>.+))?$", item)
        if match is None:
            continue
        name = match.group("name")
        expr = match.group("expr")
        if expr:
            value = _eval_int_expression(expr, symbols)
            if value is None:
                continue
            current = value
        else:
            current += 1
        symbols[name] = current
        values.setdefault(str(current), name)
    return values


def _extract_typedef_structs(text: str, header_path: Path) -> dict[str, dict[str, object]]:
    structures = {}
    stripped = _strip_comments(text)
    pattern = re.compile(r"typedef\s+struct(?:\s+(?P<tag>_[A-Za-z][A-Za-z0-9_]*))?\s*\{")
    for match in pattern.finditer(stripped):
        open_index = stripped.find("{", match.start())
        close_index = _find_matching_brace(stripped, open_index)
        if close_index < 0:
            continue
        semicolon_index = stripped.find(";", close_index)
        if semicolon_index < 0:
            continue
        tag = match.group("tag") or ""
        aliases = stripped[close_index + 1 : semicolon_index]
        name = _select_typedef_name(tag, aliases)
        if not name:
            continue
        body = stripped[open_index + 1 : close_index]
        fields = _parse_struct_fields(body)
        metadata: dict[str, object] = {
            "source_header": str(header_path),
        }
        if fields:
            metadata["fields"] = fields
        else:
            metadata["opaque"] = True
        structures[name] = metadata
    return structures


def _parse_struct_fields(body: str) -> list[dict[str, str]]:
    fields = []
    for item in _split_top_level(body, ";"):
        cleaned = _normalize_space(item)
        if not cleaned or "{" in cleaned or "}" in cleaned or cleaned.startswith("#"):
            continue
        if cleaned.startswith("DECLSPEC_ALIGN"):
            cleaned = re.sub(r"^DECLSPEC_ALIGN\([^)]*\)\s*", "", cleaned)
        if ":" in cleaned:
            continue
        match = re.match(r"(?P<type>.+?)(?P<name>[A-Za-z_][A-Za-z0-9_]*)(?P<array>(?:\[[^\]]*\])*)$", cleaned)
        if match is None:
            fields.append({"raw": cleaned})
            continue
        field_type = _normalize_space(match.group("type")).strip()
        field_name = match.group("name")
        array_suffix = match.group("array") or ""
        field_type = field_type.rstrip("* ")
        if "*" in match.group("type") and not field_type.endswith("*"):
            field_type += "*"
        field = {
            "type": field_type,
            "name": field_name,
        }
        if array_suffix:
            field["array"] = array_suffix
        fields.append(field)
    return fields


def _select_typedef_name(tag: str, aliases: str) -> str:
    alias_names = re.findall(r"\*?\s*([A-Za-z_][A-Za-z0-9_]*)", aliases)
    non_pointer_aliases = [name for name in alias_names if not name.startswith("P")]
    if non_pointer_aliases:
        return _normalize_type_name(non_pointer_aliases[0])
    if tag:
        return _normalize_type_name(tag)
    return _normalize_type_name(alias_names[0]) if alias_names else ""


def _normalize_type_name(name: str) -> str:
    if name.startswith("_"):
        return name[1:]
    return name


def _eval_int_expression(expr: str, symbols: dict[str, int]) -> int | None:
    cleaned = expr.strip()
    cleaned = re.sub(r"(?i)\b(0x[0-9a-f]+|\d+)(ui64|i64|ull|llu|ul|lu|u|l)\b", r"\1", cleaned)
    cleaned = re.sub(r"\((?:U?CHAR|U?SHORT|U?LONG|ULONG_PTR|SIZE_T|NTSTATUS|int|long|unsigned|signed)\)", "", cleaned)
    for name, value in sorted(symbols.items(), key=lambda item: len(item[0]), reverse=True):
        cleaned = re.sub(r"\b%s\b" % re.escape(name), str(value), cleaned)
    if not re.fullmatch(r"[0-9A-Fa-fxX\s|&~<>()+\-*/]+", cleaned):
        return None
    try:
        node = ast.parse(cleaned, mode="eval")
        return _eval_int_ast(node.body)
    except (SyntaxError, ValueError, TypeError, ZeroDivisionError, OverflowError):
        return None


def _eval_int_ast(node: ast.AST) -> int:
    if isinstance(node, ast.Constant) and isinstance(node.value, int) and not isinstance(node.value, bool):
        return int(node.value)
    if isinstance(node, ast.UnaryOp):
        value = _eval_int_ast(node.operand)
        if isinstance(node.op, ast.UAdd):
            return value
        if isinstance(node.op, ast.USub):
            return -value
        if isinstance(node.op, ast.Invert):
            return ~value
    if isinstance(node, ast.BinOp):
        left = _eval_int_ast(node.left)
        right = _eval_int_ast(node.right)
        if isinstance(node.op, ast.BitOr):
            return left | right
        if isinstance(node.op, ast.BitAnd):
            return left & right
        if isinstance(node.op, ast.LShift):
            if right < 0:
                raise ValueError("negative shift")
            return left << right
        if isinstance(node.op, ast.RShift):
            if right < 0:
                raise ValueError("negative shift")
            return left >> right
        if isinstance(node.op, ast.Add):
            return left + right
        if isinstance(node.op, ast.Sub):
            return left - right
        if isinstance(node.op, ast.Mult):
            return left * right
        if isinstance(node.op, (ast.Div, ast.FloorDiv)):
            return _truncating_int_divide(left, right)
    raise ValueError("unsupported integer expression")


def _truncating_int_divide(left: int, right: int) -> int:
    if right == 0:
        raise ZeroDivisionError("integer division by zero")
    sign = -1 if (left < 0) ^ (right < 0) else 1
    return sign * (abs(left) // abs(right))


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    text = re.sub(r"//.*", " ", text)
    return text


def _function_declaration_scan_text(text: str) -> str:
    without_comments = _blank_comments_preserve_length(text)
    return _blank_preprocessor_lines_preserve_length(without_comments)


def _blank_comments_preserve_length(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", lambda match: _blank_match(match.group(0)), text, flags=re.DOTALL)
    text = re.sub(r"//.*", lambda match: _blank_match(match.group(0)), text)
    return text


def _blank_preprocessor_lines_preserve_length(text: str) -> str:
    lines = []
    in_directive = False
    for line in text.splitlines(keepends=True):
        starts_directive = line.lstrip().startswith("#")
        if starts_directive or in_directive:
            lines.append(_blank_match(line))
        else:
            lines.append(line)
        in_directive = (starts_directive or in_directive) and line.rstrip("\r\n").rstrip().endswith("\\")
    return "".join(lines)


def _blank_match(value: str) -> str:
    return "".join("\n" if char == "\n" else " " for char in value)


def _looks_like_prose_type(return_type: str) -> bool:
    words = re.findall(r"[A-Za-z_][A-Za-z0-9_]*", return_type)
    if len(words) > 4:
        return True
    lowered = {word.lower() for word in words}
    prose_words = {
        "abstract",
        "contains",
        "definitions",
        "handled",
        "manager",
        "mentioned",
        "variable",
    }
    return bool(lowered & prose_words)


def _find_declaration_start(text: str, function_line_start: int) -> int:
    lines = text[:function_line_start].splitlines(keepends=True)
    offset = function_line_start
    selected = []
    skipped_blank_lines = 0
    for line in reversed(lines):
        stripped = line.strip()
        offset -= len(line)
        if not stripped:
            if selected and skipped_blank_lines < 1 and line.rstrip("\r\n"):
                skipped_blank_lines += 1
                continue
            break
        if stripped.startswith("#"):
            break
        if selected and (stripped.endswith(";") or stripped.startswith("}")):
            break
        selected.append((offset, stripped))
        if len(selected) >= 12:
            break
    if not selected:
        return function_line_start
    return selected[-1][0]


def _parse_return_type(prefix: str) -> tuple[str, str]:
    lines = [_strip_sal(line.strip()) for line in prefix.splitlines()]
    storage_tokens = {
        "NTKERNELAPI",
        "NTSYSAPI",
        "DECLSPEC_RESTRICT",
        "DECLSPEC_NORETURN",
        "FORCEINLINE",
        "CFORCEINLINE",
        "DECLSPEC_DEPRECATED_DDK",
        "DECLSPEC_NOINLINE",
        "EXPORT",
    }
    calling_convention_tokens = {
        "NTAPI",
        "FASTCALL",
        "APIENTRY",
        "FLTAPI",
        "WMIAPI",
        "__cdecl",
        "__stdcall",
        "__fastcall",
    }
    tokens = []
    calling_convention = ""
    for line in lines:
        if not line:
            continue
        for token in _normalize_space(line).split(" "):
            if not token:
                continue
            if token in storage_tokens:
                continue
            if token in calling_convention_tokens:
                calling_convention = token
                continue
            tokens.append(token)
    return_type = _normalize_space(" ".join(tokens))
    return return_type, calling_convention


def _parse_parameter_list(args: str) -> list[dict[str, str]]:
    params = []
    for raw_arg in _split_arguments(args):
        cleaned = _strip_sal(raw_arg)
        cleaned = _normalize_space(cleaned)
        if not cleaned or cleaned == "VOID":
            continue
        parsed = _parse_parameter(cleaned)
        if parsed:
            params.append(parsed)
    return params


def _parse_parameter(text: str) -> dict[str, str] | None:
    text = text.rstrip(",").strip()
    match = re.match(r"(?P<type>.+?)(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", text)
    if match is None:
        return None
    param_type = _normalize_space(match.group("type")).strip()
    name = match.group("name")
    param_type = param_type.rstrip("* ")
    if "*" in match.group("type") and not param_type.endswith("*"):
        param_type += "*"
    return {
        "name": name,
        "type": param_type,
    }


def _strip_sal(text: str) -> str:
    result = text
    previous = None
    while previous != result:
        previous = result
        result = _strip_comments(result)
        result = _remove_sal_macro_calls(result)
        result = re.sub(r"\b__drv_[A-Za-z0-9_]+\b", " ", result)
        result = re.sub(r"\b_[A-Za-z0-9_]+_", " ", result)
    return result


def _remove_sal_macro_calls(text: str) -> str:
    result = []
    index = 0
    length = len(text)
    while index < length:
        if text[index] not in {"_"}:
            result.append(text[index])
            index += 1
            continue

        name_end = index + 1
        while name_end < length and (text[name_end].isalnum() or text[name_end] == "_"):
            name_end += 1
        name = text[index:name_end]
        if not _is_sal_macro_name(name):
            result.append(text[index])
            index += 1
            continue

        scan = name_end
        while scan < length and text[scan].isspace():
            scan += 1
        if scan >= length or text[scan] != "(":
            result.append(" ")
            index = name_end
            continue

        close_index = _find_matching_parenthesis(text, scan)
        if close_index < 0:
            result.append(" ")
            index = name_end
            continue

        result.append(" ")
        index = close_index + 1
    return "".join(result)


def _is_sal_macro_name(name: str) -> bool:
    if name.startswith("__drv_"):
        return True
    if name.startswith("_") and name.endswith("_") and len(name) > 2:
        return True
    return False


def _split_arguments(argument_text: str) -> list[str]:
    args = []
    current = []
    depth = 0
    for char in argument_text:
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        if char == "," and depth == 0:
            args.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    if current or argument_text.strip():
        args.append("".join(current).strip())
    return args


def _split_top_level(text: str, separator: str) -> list[str]:
    parts = []
    current = []
    paren_depth = 0
    brace_depth = 0
    bracket_depth = 0
    for char in text:
        if char == "(":
            paren_depth += 1
        elif char == ")":
            paren_depth = max(0, paren_depth - 1)
        elif char == "{":
            brace_depth += 1
        elif char == "}":
            brace_depth = max(0, brace_depth - 1)
        elif char == "[":
            bracket_depth += 1
        elif char == "]":
            bracket_depth = max(0, bracket_depth - 1)
        if char == separator and paren_depth == 0 and brace_depth == 0 and bracket_depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    if current or text.strip():
        parts.append("".join(current).strip())
    return parts


def _find_matching_parenthesis(text: str, open_index: int) -> int:
    depth = 0
    for index in range(open_index, len(text)):
        char = text[index]
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return index
    return -1


def _find_matching_brace(text: str, open_index: int) -> int:
    depth = 0
    for index in range(open_index, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return index
    return -1


def _normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _print_summary(profile: dict[str, Any], verbose: bool = False) -> None:
    functions = profile.get("functions", {})
    enums = profile.get("enums", {})
    structures = profile.get("structures", {})
    aliases = profile.get("aliases", {})
    macros = profile.get("macros", {})
    symbols = profile.get("symbols", {})
    headers = profile.get("source", {}).get("headers", []) if isinstance(profile.get("source"), dict) else []
    print("kernel API profile summary")
    print("  headers: %d" % (len(headers) if isinstance(headers, list) else 0))
    print("  functions: %d" % (len(functions) if isinstance(functions, dict) else 0))
    print("  enums: %d" % (len(enums) if isinstance(enums, dict) else 0))
    print("  structures: %d" % (len(structures) if isinstance(structures, dict) else 0))
    print("  aliases: %d" % (len(aliases) if isinstance(aliases, dict) else 0))
    print("  macros: %d" % (len(macros) if isinstance(macros, dict) else 0))
    print("  symbols: %d" % (len(symbols) if isinstance(symbols, dict) else 0))
    if verbose and isinstance(functions, dict):
        for name in sorted(functions):
            metadata = functions[name]
            params = metadata.get("params", []) if isinstance(metadata, dict) else []
            print("  - %s(%d params)" % (name, len(params) if isinstance(params, list) else 0))


if __name__ == "__main__":
    raise SystemExit(main())
